image: "golang:alpine"
stages:
  - "build"

go-build:
  stage: "build"
  image: "cr.simoncor.net/siempie/go-build:latest"
  script:
    - "GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o goplayer main.go"
    - "zip goplayer.zip goplayer"
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}"
    paths:
      - "goplayer.zip"
