image: "golang:alpine"
stages:
  - "build"

go-build:
  stage: "build"
  script:
    - "GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o goplayer main.go"
    - "zip goplayer.zip goplayer"
  artifacts:
    paths:
      - "main.zip"
